gui: update __init__ to use super() (bug 1836097)
mozilla/mozregression pull request #1319
Opened 2023-05-31 17:44 UTC by zzzeid

2023-05-31 21:20 UTC, cgsheeh requested changes
Is there any difference in behaviour between between `BaseClass.__init__` and `super().__init__` for classes that are only single inheritance? I think it probably makes sense to switch over all use cases to `super().__init__` if possible, regardless of whether they use multiple inheritance or not, to keep things consistent. I was also under the impression `super().__init__` is the standard way to do call the constructor for a superclass.

2023-06-01 11:56 UTC, zzzeid commented
> Is there any difference in behaviour between between `BaseClass.__init__` and `super().__init__` for classes that are only single inheritance? I think it probably makes sense to switch over all use cases to `super().__init__` if possible, regardless of whether they use multiple inheritance or not, to keep things consistent. I was also under the impression `super().__init__` is the standard way to do call the constructor for a superclass.

This bug was affecting things that have multiple base classes that also include `QObject`. I changed all of those, we should file a separate bug to modernize the rest of the code since it is not currently broken and would be outside the scope of this bug.

2023-06-01 12:10 UTC, zzzeid commented
> Is there any difference in behaviour between between `BaseClass.__init__` and `super().__init__` for classes that are only single inheritance?

For more context, this newer PySide6 release added support for this more standard way of using `super()`. Previously this would not have worked. From the dev notes:

> Actually, multiple inheritance in PySide has nothing to do with Python, but users expect the super() function to behave the same way when used in a PySide class as in a normal Python class. We have extended the __init__ function accordingly

Nonetheless we should switch everything to use `super()` to keep things more clean. Filed [bug 1836252](https://bugzilla.mozilla.org/show_bug.cgi?id=1836252).

2023-06-01 14:31 UTC, cgsheeh approved these changes

2023-06-01 14:31 UTC, cgsheeh commented on gui/mozregui/bisection.py
> +            dl_in_background=download_in_background,
`dl_in_background` isn't passed as an argument anywhere, why is it needed now?

2023-06-01 14:56 UTC, merged